### ISSUE TITLE
导入时出错

### ISSUE THREAD

**Issue by wkatios** [lzjun567/zhihu-api#38]
>>> from zhihu import Account
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\zhihu\__init__.py", line 1, in <module>
    from zhihu.models import answer
  File "C:\Python27\lib\site-packages\zhihu\models\__init__.py", line 22, in <module>
    from zhihu.error import ZhihuError
  File "C:\Python27\lib\site-packages\zhihu\models\zhihu.py", line 6, in <module>
    from ..auth import need_login
  File "C:\Python27\lib\site-packages\zhihu\auth.py", line 6, in <module>
    from zhihu.models.account import Account
  File "C:\Python27\lib\site-packages\zhihu\models\account.py", line 6, in <module>
    from ..models import Model
ImportError: cannot import name Model

**Comment by william-tu** [comment]
都说了是用python3了

**Comment by lzjun567** [comment]
fixed
